name: smf_contracts
description: Contracts, DSL, and shared codegen interfaces used across SMF modules (routing, DI, code generation).
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [dsl, codegen, routing, dependency-injection, interfaces]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  smf_contribution_engine: ^0.1.0
  mason: ^0.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
