name: smf_contracts
description: Contracts, DSL, and shared codegen interfaces used across SMF modules (routing, DI, code generation).
version: 0.1.0
repository: https://github.com/saymyframe/smf_modules
homepage: https://saymyframe.com
issue_tracker: https://github.com/saymyframe/smf_modules/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  smf_contribution_engine:
    path: ../smf_modules/smf_contribution_engine
  mason: ^0.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
